/**
 * seed-normas.js
 * Genera 20 requerimientos legales basados en los archivos de la carpeta /Normas
 * Uso: node prisma/seed-normas.js
 */
require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const daysFrom = (d) => new Date(Date.now() + d * 24 * 60 * 60 * 1000);

async function main() {
  console.log('🌱 Cargando requerimientos desde archivos de normas...\n');

  // Obtener empresa 1
  const company = await prisma.company.findFirst({
    where: { name: { contains: 'Manufacturas' } },
  });
  if (!company) throw new Error('No se encontró la empresa Manufacturas del Norte');

  const admin = await prisma.user.findFirst({
    where: { role: 'ADMIN', companyId: company.id },
  });
  if (!admin) throw new Error('No se encontró usuario admin');

  const reqs = [
    {
      code: 'NOM-001-STPS-2008',
      name: 'Edificios, locales, instalaciones y áreas',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.2, 5.3, 7.5.1 h) y 8.3',
      area: 'General',
      responsibleArea: 'Mantenimiento',
      status: 'PENDING',
      dueDate: daysFrom(90),
      normName: 'Norma Oficial Mexicana NOM-001-STPS-2008, Edificios, locales, instalaciones y áreas en los centros de trabajo — Condiciones de seguridad.',
      normObjective: 'Establecer las condiciones de seguridad que deben cumplir los edificios, locales, instalaciones y áreas de los centros de trabajo para evitar riesgos que provoquen daños a la integridad física de los trabajadores o deterioro a las instalaciones.',
      applicabilityJustification: 'La empresa cuenta con instalaciones industriales que incluyen edificios de manufactura, almacenes y áreas de servicio, las cuales deben mantenerse en condiciones seguras conforme a la norma.',
      applicabilityScope: 'Aplica a todos los edificios, locales, instalaciones y áreas: planta de producción, almacenes, talleres de mantenimiento, oficinas administrativas y zonas de tránsito.',
      specificRequirement: 'Realizar verificaciones oculares anuales por área (numeral 5.2), efectuar verificaciones posteriores a eventos que puedan dañar las instalaciones como sismos o inundaciones (numeral 5.3), dar mantenimiento semestral a puertas de emergencia exteriores (numeral 7.5.1 h) y contar con programa anual de mantenimiento al sistema de ventilación artificial (numeral 8.3). Conservar bitácoras y registros por un año mínimo.',
    },
    {
      code: 'NOM-002-STPS-2010',
      name: 'Prevención y protección contra incendios',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.1–5.11, 7.2, 7.4, 7.18, 10 y 11',
      area: 'General',
      responsibleArea: 'Seguridad e Higiene',
      status: 'IN_PROGRESS',
      dueDate: daysFrom(30),
      normName: 'Norma Oficial Mexicana NOM-002-STPS-2010, Condiciones de seguridad — Prevención y protección contra incendios en los centros de trabajo.',
      normObjective: 'Establecer los requerimientos para la prevención y protección contra incendios en los centros de trabajo, a fin de reducir los riesgos de un incendio, su propagación y las lesiones o daños que puedan causar a los trabajadores.',
      applicabilityJustification: 'El centro de trabajo cuenta con procesos productivos que utilizan materiales inflamables, equipos eléctricos industriales y almacenamiento de sustancias que representan riesgo de incendio.',
      applicabilityScope: 'Aplica a todas las áreas de la empresa: producción, almacén, oficinas administrativas y zonas de carga y descarga. Incluye a todo el personal permanente, temporal y subcontratado.',
      specificRequirement: 'Clasificar riesgo de incendio del centro de trabajo conforme al Apéndice A. Contar con extintores portátiles con revisión mensual documentada (numeral 7.2) y mantenimiento anual (numeral 7.18). Elaborar programa anual de revisión de equipos contra incendio, instalaciones eléctricas e instalaciones de gas (numerales 7.4, 7.5, 7.6). Elaborar plan de atención a emergencias (numeral 8). Realizar simulacros: mínimo 1 anual en riesgo ordinario o 2 anuales en riesgo alto (numerales 5.7, 10). Programa anual de capacitación en prevención y combate de incendios (numeral 11). Conservar registros 3 años.',
    },
    {
      code: 'NOM-004-STPS-1999',
      name: 'Protección en maquinaria y equipo',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.2, 5.3, 7.1, 7.2.2, 7.2.3',
      area: 'Producción',
      responsibleArea: 'Mantenimiento',
      status: 'IN_PROGRESS',
      dueDate: daysFrom(60),
      normName: 'Norma Oficial Mexicana NOM-004-STPS-1999, Sistemas de protección y dispositivos de seguridad en la maquinaria y equipo que se utilice en los centros de trabajo.',
      normObjective: 'Establecer las condiciones de seguridad y los sistemas de protección y dispositivos que deberá tener la maquinaria y equipo del centro de trabajo, para evitar accidentes a los trabajadores que los operen o realicen labores de mantenimiento.',
      applicabilityJustification: 'La empresa opera maquinaria de manufactura metalmecánica (tornos, fresadoras, prensas, sierras) que representa riesgo de atrapamiento, corte y aplastamiento para los operadores.',
      applicabilityScope: 'Aplica a toda la maquinaria y equipo instalado en el área de producción y taller de mantenimiento. Incluye operadores, mecánicos de mantenimiento y supervisores de área.',
      specificRequirement: 'Elaborar estudio de riesgo potencial de la maquinaria y equipo (numeral 5.2). Elaborar, difundir y cumplir el Programa Específico de Seguridad e Higiene para la Operación y Mantenimiento de la Maquinaria (numeral 5.3). Definir periodicidad de mantenimiento preventivo en el programa (numeral 7.2.2). Llevar registro de mantenimiento preventivo y correctivo con fecha de ejecución, conservándolo al menos 12 meses (numeral 7.2.3). Aplicar procedimiento de bloqueo de energía antes y durante el mantenimiento.',
    },
    {
      code: 'NOM-005-STPS-1998',
      name: 'Manejo de sustancias químicas peligrosas',
      legalSource: 'NOM',
      legalBasis: 'Capítulos 5, 7, 8 y 9',
      area: 'Producción',
      responsibleArea: 'Seguridad e Higiene',
      status: 'PENDING',
      dueDate: daysFrom(120),
      normName: 'Norma Oficial Mexicana NOM-005-STPS-1998, Relativa a las condiciones de seguridad e higiene en los centros de trabajo para el manejo, transporte y almacenamiento de sustancias químicas peligrosas.',
      normObjective: 'Establecer las condiciones de seguridad e higiene para el manejo, transporte y almacenamiento de sustancias químicas peligrosas, a fin de prevenir y proteger la vida y la salud de los trabajadores.',
      applicabilityJustification: 'El centro de trabajo utiliza solventes, lubricantes, refrigerantes y otros productos químicos industriales en sus procesos de manufactura metalmecánica, que presentan características de inflamabilidad, corrosividad o toxicidad.',
      applicabilityScope: 'Aplica a todas las áreas donde se manejen, transporten o almacenen sustancias químicas peligrosas: producción, almacén, mantenimiento y áreas de servicio.',
      specificRequirement: 'Elaborar y mantener actualizado estudio de riesgos potenciales de las sustancias químicas peligrosas (numeral 5.2). Elaborar y aplicar Programa Específico de Seguridad e Higiene para Manejo de Sustancias Químicas (numeral 5.12). Programa de mantenimiento preventivo a equipos e instalaciones relacionados, con registros conservados al menos 12 meses. Capacitación al ingreso, al cambiar de puesto y periódicamente. Exámenes médicos de ingreso, periódicos y especiales (numeral 5). Contar con plan de atención a emergencias químicas actualizado. Mantener Hojas de Datos de Seguridad accesibles para trabajadores.',
    },
    {
      code: 'NOM-006-STPS-2014',
      name: 'Manejo y almacenamiento de materiales',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.1, 5.9, 7.8.1, 10 y 11',
      area: 'Almacén',
      responsibleArea: 'Almacén',
      status: 'PENDING',
      dueDate: daysFrom(90),
      normName: 'Norma Oficial Mexicana NOM-006-STPS-2014, Manejo y almacenamiento de materiales — Condiciones de seguridad y salud en el trabajo.',
      normObjective: 'Establecer las condiciones de seguridad y salud en el trabajo que se deberán cumplir en los centros de trabajo para evitar riesgos a los trabajadores y daños a las instalaciones por las actividades de manejo y almacenamiento de materiales.',
      applicabilityJustification: 'La empresa realiza manejo y almacenamiento de materiales metálicos, insumos industriales y productos terminados utilizando montacargas, polipastos y maniobras manuales, actividades que generan riesgo de aplastamiento, caída de materiales y esfuerzo físico excesivo.',
      applicabilityScope: 'Aplica a las áreas de almacén, producción y carga/descarga. Incluye operadores de montacargas, almacenistas y trabajadores que realizan manejo manual de materiales.',
      specificRequirement: 'Contar con programa específico de revisión y mantenimiento de la maquinaria de manejo de materiales con registros mínimo 12 meses (numerales 5.1, 7.1). Realizar revisión visual y prueba funcional de maquinaria al inicio de cada jornada laboral (numeral 7.8.1). Vigilancia a la salud de trabajadores expuestos a sobreesfuerzo con exámenes médicos de ingreso, periódicos y especiales (numeral 10). Capacitación al ingreso, al cambiar de puesto y al introducir nueva maquinaria (numeral 11). Asegurar condiciones de estantería y almacenamiento conforme al capítulo 9.',
    },
    {
      code: 'NOM-009-STPS-2011',
      name: 'Trabajos en altura',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.7, 7.14, 7.15, 8, 14, 15 y 16',
      area: 'Mantenimiento',
      responsibleArea: 'Mantenimiento',
      status: 'PENDING',
      dueDate: daysFrom(60),
      normName: 'Norma Oficial Mexicana NOM-009-STPS-2011, Condiciones de seguridad para realizar trabajos en altura.',
      normObjective: 'Establecer los requerimientos mínimos de seguridad para la prevención de riesgos laborales por la realización de trabajos en altura, es decir, actividades a más de 1.80 m sobre el nivel de referencia.',
      applicabilityJustification: 'El personal de mantenimiento realiza trabajos en techos, estructuras y equipos a alturas mayores a 1.80 m para reparaciones, instalaciones y limpieza de maquinaria e instalaciones industriales.',
      applicabilityScope: 'Aplica a todo el personal de mantenimiento, contratistas y supervisores que realicen trabajos en altura dentro de las instalaciones de la empresa.',
      specificRequirement: 'Establecer y aplicar programa de revisión y mantenimiento a sistemas y equipos de trabajos en altura (numeral 5.7, 7.14). Llevar registros de revisiones y mantenimiento preventivo/correctivo conservados al menos 12 meses (numeral 7.15). Revisar sistemas o equipos al inicio de cada jornada y antes de cada uso (numerales 7.3, 8.4.3). Realizar revisión anual de todos los sistemas o equipos (numeral 7.14). Practicar exámenes médicos a trabajadores que realizan trabajos en altura: de ingreso y periódicos (numeral 14). Contar con plan de atención a emergencias para trabajos en altura (numeral 15). Proporcionar autorización escrita para cada trabajo en altura con andamios o plataformas (numeral 7.2). Capacitación y adiestramiento al ingreso y periódicamente (numeral 16).',
    },
    {
      code: 'NOM-010-STPS-2014',
      name: 'Agentes químicos contaminantes del ambiente laboral',
      legalSource: 'NOM',
      legalBasis: 'Capítulos estudio de agentes, evaluación, control y vigilancia a la salud',
      area: 'Producción',
      responsibleArea: 'Seguridad e Higiene',
      status: 'PENDING',
      dueDate: daysFrom(180),
      normName: 'Norma Oficial Mexicana NOM-010-STPS-2014, Agentes químicos contaminantes del ambiente laboral — Reconocimiento, evaluación y control.',
      normObjective: 'Establecer los procesos para reconocer, evaluar y controlar los agentes químicos contaminantes del ambiente laboral, con el fin de prevenir daños a la salud de los trabajadores.',
      applicabilityJustification: 'Los procesos de manufactura metalmecánica generan contaminantes químicos en el ambiente de trabajo como humos metálicos, vapores de solventes, nieblas de aceite y polvos metálicos que pueden afectar la salud respiratoria de los trabajadores.',
      applicabilityScope: 'Aplica a todas las áreas con generación de contaminantes químicos: producción, soldadura, pintura y mantenimiento. Incluye a todos los trabajadores ocupacionalmente expuestos.',
      specificRequirement: 'Elaborar y mantener actualizado estudio de agentes químicos contaminantes del ambiente laboral (identificación, propiedades, condiciones de exposición). Realizar mediciones ambientales periódicas por laboratorios acreditados y compararlas con Límites Máximos Permisibles de Exposición (LMPE). Implementar programa de control jerarquizado (técnico, administrativo y EPP). Vigilancia a la salud: exámenes de ingreso, periódicos según riesgo y especiales tras exposiciones agudas. Conservar registros del estudio de agentes químicos al menos 5 años y de mediciones y vigilancia a la salud mínimo 1 año. Capacitación periódica al ingreso y al cambiar de puesto.',
    },
    {
      code: 'NOM-011-STPS-2001',
      name: 'Ruido en centros de trabajo',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.2, 8.2, 8.3, 8.6, 8.7.2, 8.8.1',
      area: 'Producción',
      responsibleArea: 'Seguridad e Higiene',
      status: 'PENDING',
      dueDate: daysFrom(120),
      normName: 'Norma Oficial Mexicana NOM-011-STPS-2001, Condiciones de seguridad e higiene en los centros de trabajo donde se genere ruido.',
      normObjective: 'Establecer las condiciones de seguridad e higiene en los centros de trabajo donde se genere ruido capaz de alterar la salud de los trabajadores; determinar los niveles máximos permisibles de exposición por jornada e implementar un programa de conservación de la audición.',
      applicabilityJustification: 'Los equipos de manufactura metalmecánica (prensas, tornos, fresadoras, sierra, equipos de soldadura) generan niveles de ruido que potencialmente superan los 80 dB(A), con exposición prolongada para los operadores.',
      applicabilityScope: 'Aplica a las áreas de producción y mantenimiento donde los niveles de ruido sean iguales o superiores a 80 dB(A). Incluye a todos los trabajadores expuestos en dichas áreas.',
      specificRequirement: 'Realizar reconocimiento y evaluación del Nivel de Exposición a Ruido (NER) en áreas con NSA ≥ 80 dB(A) cada 2 años o dentro de los 90 días posteriores a cambios que modifiquen resultados (numeral 5.2). Implementar y mantener actualizado Programa de Conservación de la Audición en áreas con exposición ≥ 85 dB(A) (numeral 5.4). Realizar exámenes médicos específicos anuales a trabajadores expuestos a ≥ 85 dB(A) (numeral 8.6). Verificar efectividad de medidas de control dentro de los 30 días posteriores a su implementación (numeral 8.7.2). Conservar documentación del programa durante los últimos 5 años (numeral 8.8.1). Proporcionar EPP auditivo certificado a trabajadores con exposición ≥ 85 dB(A).',
    },
    {
      code: 'NOM-017-STPS-2008',
      name: 'Equipo de Protección Personal',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.2 al 5.8, 6.3, 6.4',
      area: 'General',
      responsibleArea: 'Seguridad e Higiene',
      status: 'IN_PROGRESS',
      dueDate: daysFrom(30),
      normName: 'Norma Oficial Mexicana NOM-017-STPS-2008, Equipo de protección personal — Selección, uso y manejo en los centros de trabajo.',
      normObjective: 'Establecer los requisitos mínimos para que el patrón seleccione, adquiera y proporcione a sus trabajadores el equipo de protección personal correspondiente para protegerlos de los agentes del medio ambiente de trabajo que puedan dañar su integridad física y su salud.',
      applicabilityJustification: 'La empresa realiza procesos de manufactura metalmecánica que incluyen maquinado, soldadura, esmerilado y manejo de materiales, actividades que exponen al personal a riesgos de proyección de partículas, ruido, sustancias químicas y esfuerzo físico.',
      applicabilityScope: 'Aplica a todos los trabajadores del área de producción, mantenimiento y almacén. Incluye personal de planta, supervisores y contratistas que realicen actividades dentro de las instalaciones.',
      specificRequirement: 'Identificar y analizar riesgos por puesto y área, manteniendo registros actualizados mientras no cambien implementos y procesos (numeral 5.2). Determinar el EPP requerido por puesto conforme a riesgos identificados (numeral 5.3). Proporcionar EPP adecuado a todos los trabajadores expuestos de forma continua (numeral 5.4). Capacitar y adiestrar al ingreso, al introducir nuevo EPP y conforme a programa interno (numeral 5.6). Supervisar el uso de EPP durante toda la jornada (numeral 5.7). Señalizar con NOM-026 las áreas con uso obligatorio de EPP (numeral 5.8). El trabajador debe revisar su EPP antes de iniciar, durante y al finalizar cada turno (numeral 6.3) y reportar deterioro para reemplazo inmediato (numeral 6.4).',
    },
    {
      code: 'NOM-018-STPS-2015',
      name: 'Sistema armonizado para identificación de peligros por sustancias químicas',
      legalSource: 'NOM',
      legalBasis: 'Capítulo operativo: clasificación, etiquetado, HDS y señalización',
      area: 'General',
      responsibleArea: 'Seguridad e Higiene',
      status: 'PENDING',
      dueDate: daysFrom(90),
      normName: 'Norma Oficial Mexicana NOM-018-STPS-2015, Sistema armonizado para la identificación y comunicación de peligros y riesgos por sustancias químicas peligrosas en los centros de trabajo.',
      normObjective: 'Establecer los requisitos para disponer en los centros de trabajo del sistema armonizado de identificación y comunicación de peligros y riesgos por sustancias químicas peligrosas, con el fin de prevenir daños a los trabajadores y al personal que actúa en caso de emergencia.',
      applicabilityJustification: 'La empresa maneja diversas sustancias químicas peligrosas en sus procesos: solventes, lubricantes, refrigerantes y materiales de soldadura, que requieren ser correctamente clasificados, etiquetados y comunicados al personal conforme al sistema GHS.',
      applicabilityScope: 'Aplica a todos los centros de trabajo donde se manejen sustancias químicas peligrosas o mezclas: producción, almacén, mantenimiento y cualquier área donde se utilicen o almacenen sustancias con peligros físicos o para la salud.',
      specificRequirement: 'Implementar el sistema armonizado de identificación y comunicación de peligros basado en GHS (clasificación, etiquetado con pictogramas, palabras de advertencia y frases H y P, Hojas de Datos de Seguridad de 16 secciones). Contar con HDS de todas las sustancias químicas peligrosas y mezclas manejadas, disponibles permanentemente para trabajadores en áreas de uso. Señalizar depósitos, recipientes y áreas de almacenamiento permanentemente. Actualizar HDS, etiquetas y señalización cuando cambien sustancias, proveedores o formulaciones. Capacitar a trabajadores al ingreso, al cambiar de puesto o al introducir nuevas sustancias, y conforme a programa anual.',
    },
    {
      code: 'NOM-019-STPS-2011',
      name: 'Comisión Mixta de Seguridad e Higiene (CMSH)',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.1, 5.6, 7, 8, capítulos programa y recorridos',
      area: 'General',
      responsibleArea: 'Seguridad e Higiene',
      status: 'IN_PROGRESS',
      dueDate: daysFrom(30),
      normName: 'Norma Oficial Mexicana NOM-019-STPS-2011, Constitución, integración, organización y funcionamiento de las comisiones de seguridad e higiene en los centros de trabajo.',
      normObjective: 'Establecer los requerimientos para la constitución, integración, organización y funcionamiento de las comisiones de seguridad e higiene en los centros de trabajo, con el fin de identificar las causas de los accidentes y enfermedades de trabajo y proponer medidas preventivas.',
      applicabilityJustification: 'Todo centro de trabajo con más de un trabajador está obligado a conformar una Comisión Mixta de Seguridad e Higiene conforme a lo dispuesto por el artículo 509 de la Ley Federal del Trabajo y la NOM-019.',
      applicabilityScope: 'Aplica a la totalidad de la plantilla laboral y a todos los niveles jerárquicos de la organización. El comité estará integrado por representantes del patrón y de los trabajadores.',
      specificRequirement: 'Constituir e integrar formalmente la CMSH con acta de constitución (numeral 5.1). Elaborar programa anual de recorridos de verificación en todas las áreas y turnos (numeral 8.2). Realizar recorridos ordinarios de verificación conforme al programa anual con elaboración de actas (numeral 8). Realizar recorridos extraordinarios ante accidentes graves, cambios de instalaciones o reportes de condiciones peligrosas. Capacitar a los integrantes de la CMSH al menos una vez al año; curso de inducción inmediato a integrantes nuevos (numeral 5.6). Conservar actas de constitución, recorridos, investigación de accidentes y reuniones durante el período establecido por normativa.',
    },
    {
      code: 'NOM-020-STPS-2011',
      name: 'Recipientes sujetos a presión y generadores de vapor',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.4, 5.10, 10, 13, 14, 17, 18',
      area: 'Mantenimiento',
      responsibleArea: 'Mantenimiento',
      status: 'PENDING',
      dueDate: daysFrom(180),
      normName: 'Norma Oficial Mexicana NOM-020-STPS-2011, Recipientes sujetos a presión, recipientes criogénicos y generadores de vapor o calderas — Funcionamiento y condiciones de seguridad.',
      normObjective: 'Establecer los requisitos de seguridad para el funcionamiento de los recipientes sujetos a presión, recipientes criogénicos y generadores de vapor o calderas en los centros de trabajo, a fin de prevenir riesgos a los trabajadores y daños en las instalaciones.',
      applicabilityJustification: 'La empresa cuenta con recipientes sujetos a presión (compresor de aire, recipientes de gas) y sistemas de vapor utilizados en los procesos de manufactura, que requieren gestión formal de seguridad conforme a la norma.',
      applicabilityScope: 'Aplica a todos los recipientes sujetos a presión, recipientes criogénicos y generadores de vapor o calderas instalados en el centro de trabajo. Incluye personal de operación y mantenimiento.',
      specificRequirement: 'Clasificar equipos en categorías I, II o III conforme al capítulo 7. Contar con listado actualizado de equipos y expediente por cada equipo (numerales 5.2, 5.3). Elaborar y aplicar programas de revisión y mantenimiento para categorías II y III (numeral 5.4). Practicar pruebas de presión o exámenes no destructivos al menos cada 5 años y después de reparaciones (numeral 13). Demostrar funcionamiento de dispositivos de relevo de presión mediante pruebas periódicas (numeral 14). Capacitar al personal de operación, mantenimiento y pruebas (numeral 17). Registros de operación, revisión, mantenimiento y pruebas conservados 5 a 10 años (numeral 18). Dar aviso a STPS sobre equipos categoría III (numeral 16).',
    },
    {
      code: 'NOM-021-STPS-1994',
      name: 'Reporte de riesgos de trabajo',
      legalSource: 'NOM',
      legalBasis: 'Numerales 3.1.1, 3.1.3, 3.1.4, formularios CM-2A y CM-2B',
      area: 'General',
      responsibleArea: 'Recursos Humanos',
      status: 'PENDING',
      dueDate: daysFrom(365),
      normName: 'Norma Oficial Mexicana NOM-021-STPS-1994, Requerimientos y características de los informes de los riesgos de trabajo que ocurran, para integrar las estadísticas.',
      normObjective: 'Establecer los requerimientos y características de informes de los riesgos de trabajo que ocurran para que las autoridades del trabajo lleven una estadística nacional de los mismos.',
      applicabilityJustification: 'La empresa está obligada a notificar y documentar todos los riesgos de trabajo que ocurran (accidentes y enfermedades laborales) conforme a la Ley Federal del Trabajo artículo 504 y a la presente norma.',
      applicabilityScope: 'Aplica a toda la organización. Involucra a Recursos Humanos, Seguridad e Higiene y a la Comisión Mixta de Seguridad e Higiene en el proceso de reporte e investigación.',
      specificRequirement: 'Dar aviso a la STPS dentro de las 72 horas siguientes de ocurrido un accidente de trabajo o detección de una enfermedad de trabajo (numeral 3.1.1). Comunicar a la CMSH cada accidente o enfermedad detectada (numeral 3.1.3). Llevar registro interno actualizado de todos los avisos de accidentes y enfermedades de trabajo (numeral 3.1.4). Llenar y remitir al Centro Nacional de Información y Estadísticas del Trabajo el formulario CM-2A dentro de 72 horas del accidente y el CM-2B dentro de 72 horas de conocida el alta médica o defunción.',
    },
    {
      code: 'NOM-025-STPS-2008',
      name: 'Condiciones de iluminación',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.3 al 5.10, capítulos 8, 9, 10, 11 y 12',
      area: 'General',
      responsibleArea: 'Mantenimiento',
      status: 'PENDING',
      dueDate: daysFrom(120),
      normName: 'Norma Oficial Mexicana NOM-025-STPS-2008, Condiciones de iluminación en los centros de trabajo.',
      normObjective: 'Establecer los requerimientos de iluminación en las áreas de los centros de trabajo para contar con la cantidad de iluminación requerida para cada actividad visual y proveer un ambiente seguro y saludable.',
      applicabilityJustification: 'Las áreas de producción, inspección de calidad y oficinas requieren niveles de iluminación específicos conforme a la tabla de valores mínimos de la norma para garantizar condiciones visuales seguras y productivas.',
      applicabilityScope: 'Aplica a todas las áreas del centro de trabajo: planta de producción, almacenes, oficinas administrativas, talleres y zonas de tránsito.',
      specificRequirement: 'Efectuar reconocimiento de condiciones de iluminación en todas las áreas y puestos de trabajo (numeral 5.3). Realizar evaluación de niveles de iluminación con luxómetro calibrado, comparando contra Tabla 1 de la norma (numeral 5.5). Elaborar y ejecutar programa de mantenimiento de luminarias, incluyendo sistemas de emergencia (numeral 5.10). Instalar y mantener sistemas de iluminación de emergencia en áreas críticas y rutas de evacuación (numeral 5.11). Practicar exámenes médicos anuales de agudeza visual, campimetría y percepción de colores a trabajadores en áreas con iluminación especial (numeral 5.9). Aplicar medidas de control cuando se detecten deficiencias o deslumbramientos y realizar nueva evaluación (numeral 10). Conservar informe del estudio mientras no cambien las condiciones.',
    },
    {
      code: 'NOM-026-STPS-2008',
      name: 'Colores y señales de seguridad e identificación de tuberías',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.2, 5.3, 5.4, capítulos 7, 8 y 9',
      area: 'General',
      responsibleArea: 'Seguridad e Higiene',
      status: 'PENDING',
      dueDate: daysFrom(60),
      normName: 'Norma Oficial Mexicana NOM-026-STPS-2008, Colores y señales de seguridad e higiene, e identificación de riesgos por fluidos conducidos en tuberías.',
      normObjective: 'Establecer los requerimientos en cuanto a los colores y señales de seguridad e higiene y la identificación de riesgos por fluidos conducidos en tuberías en los centros de trabajo.',
      applicabilityJustification: 'La empresa cuenta con redes de tuberías que conducen fluidos como aire comprimido, aceites, agua, gas y posiblemente fluidos peligrosos, así como áreas que requieren señalización de seguridad para prevenir accidentes.',
      applicabilityScope: 'Aplica a todas las instalaciones del centro de trabajo: líneas de tuberías, áreas de producción, almacén, rutas de evacuación y equipos de emergencia que requieran señalización conforme a la norma.',
      specificRequirement: 'Implementar y mantener sistema de colores y señales de seguridad conforme a los capítulos 7 y 8 de la norma (rojo: paro/emergencia, amarillo: advertencia, verde: condición segura, azul: obligación). Identificar todas las tuberías con color de seguridad, bandas/etiquetas, información complementaria y flechas de dirección de flujo conforme al capítulo 9. Mantener visibilidad y legibilidad de señales y señalización de tuberías permanentemente (numeral 5.3). Capacitar a trabajadores sobre la correcta interpretación de colores y señales (numeral 5.2). Actualizar señalización cuando cambien fluidos, riesgos o distribución de tuberías. Renovar dictamen de unidad de verificación cada 2 años.',
    },
    {
      code: 'NOM-027-STPS-2008',
      name: 'Actividades de soldadura y corte',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.3, 5.6, 5.11, 5.15, 5.16, 10.2 h), capítulos 7, 8, 9 y 11',
      area: 'Producción',
      responsibleArea: 'Seguridad e Higiene',
      status: 'IN_PROGRESS',
      dueDate: daysFrom(45),
      normName: 'Norma Oficial Mexicana NOM-027-STPS-2008, Actividades de soldadura y corte — Condiciones de seguridad e higiene.',
      normObjective: 'Establecer condiciones de seguridad e higiene en los centros de trabajo para prevenir riesgos de trabajo durante las actividades de soldadura y corte.',
      applicabilityJustification: 'La empresa realiza procesos de soldadura y corte de metales en las áreas de producción y mantenimiento como parte de sus procesos de manufactura, actividades que generan riesgos de incendio, explosión, intoxicación por humos y daños por radiación no ionizante.',
      applicabilityScope: 'Aplica al área de producción y taller de mantenimiento donde se realizan actividades de soldadura y corte. Incluye soldadores, operadores de corte y sus supervisores directos.',
      specificRequirement: 'Elaborar análisis de riesgos potenciales para las actividades de soldadura y corte (capítulo 7). Contar con programa de actividades de soldadura y corte con procedimientos y controles (capítulo 9). Informar a trabajadores sobre riesgos al menos 2 veces al año con registro (numeral 5.3). Capacitar y adiestrar a trabajadores y supervisores al menos 1 vez al año (numeral 5.6). Capacitar al personal de rescate al menos 1 vez al año (numeral 5.11). Realizar revisiones mensuales al equipo de soldadura y corte con registro (numeral 10.2 h). Someter a trabajadores a exámenes médicos específicos al menos cada 12 meses (numeral 5.15). Conservar copias de autorizaciones para trabajos en áreas peligrosas al menos 1 año.',
    },
    {
      code: 'NOM-029-STPS-2011',
      name: 'Mantenimiento de instalaciones eléctricas',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.1 al 5.x, capítulo 7, programa de revisión y conservación',
      area: 'Mantenimiento',
      responsibleArea: 'Mantenimiento',
      status: 'PENDING',
      dueDate: daysFrom(60),
      normName: 'Norma Oficial Mexicana NOM-029-STPS-2011, Mantenimiento de las instalaciones eléctricas en los centros de trabajo — Condiciones de seguridad.',
      normObjective: 'Establecer las condiciones de seguridad para la realización de actividades de mantenimiento de las instalaciones eléctricas en los centros de trabajo, a fin de evitar accidentes al personal responsable de ejecutarlas y a personas ajenas que pudieran estar expuestas.',
      applicabilityJustification: 'El centro de trabajo cuenta con instalaciones eléctricas industriales de media y baja tensión que requieren mantenimiento periódico, actividad de alto riesgo que puede causar choques eléctricos, arcos eléctricos e incendios.',
      applicabilityScope: 'Aplica a todas las actividades de mantenimiento de instalaciones eléctricas en el centro de trabajo. Incluye al personal de mantenimiento eléctrico, contratistas especializados y sus supervisores.',
      specificRequirement: 'Contar con plan de trabajo para cada actividad de mantenimiento eléctrico con análisis de riesgos y descripción de medidas de seguridad (numerales 5.2, 7.1, 7.2). Contar con diagrama unifilar actualizado de la instalación eléctrica (numeral 5.x). Elaborar y aplicar programa de revisión y conservación de equipo, herramientas e implementos de protección aislante con fechas, responsables y resultados. Aplicar procedimientos de bloqueo y etiquetado (lockout/tagout) en cada trabajo de mantenimiento que requiera desenergización. Capacitar a trabajadores en seguridad eléctrica, procedimientos y uso de EPP con constancias DC-3, al menos anualmente en la práctica. Prohibir a menores de 16 años y mujeres gestantes la realización de estas actividades (numeral 5.1).',
    },
    {
      code: 'NOM-030-STPS-2009',
      name: 'Servicios preventivos de seguridad y salud en el trabajo',
      legalSource: 'NOM',
      legalBasis: 'Numerales 4.3, 4.4, 4.5, 4.6, 4.7, 5.7, capítulos 6 y 7',
      area: 'General',
      responsibleArea: 'Seguridad e Higiene',
      status: 'IN_PROGRESS',
      dueDate: daysFrom(15),
      normName: 'Norma Oficial Mexicana NOM-030-STPS-2009, Servicios preventivos de seguridad y salud en el trabajo — Funciones y actividades.',
      normObjective: 'Establecer las funciones y actividades que deben realizar los servicios preventivos de seguridad y salud en el trabajo para prevenir accidentes y enfermedades de trabajo en los centros laborales.',
      applicabilityJustification: 'La norma es aplicable a todos los centros de trabajo del país. Actúa como norma marco del sistema de gestión de seguridad y salud, articulando el diagnóstico, programa anual y seguimiento de las acciones preventivas y correctivas de todas las demás NOM.',
      applicabilityScope: 'Aplica a la totalidad del centro de trabajo. El responsable de seguridad y salud tiene acceso a todas las áreas, procesos y personal para identificar, evaluar y controlar los factores de riesgo.',
      specificRequirement: 'Designar responsable de seguridad y salud en el trabajo, interno o externo (numeral 4.1). Elaborar diagnóstico integral o por área de las condiciones de seguridad y salud, incluyendo condiciones físicas peligrosas, agentes del medio ambiente y requerimientos normativos aplicables (numeral 4.3, capítulo 6). Elaborar y actualizar programa de seguridad y salud al menos una vez al año (numeral 4.4, capítulo 7). Comunicar a la CMSH y a los trabajadores el diagnóstico y el contenido del programa (numeral 4.5). Elaborar reportes de seguimiento de avances y reportar al patrón por escrito al menos una vez al año (numerales 4.6, 5.7). Capacitar al personal del servicio preventivo en funciones y actividades de la norma (numeral 4.7). Conservar documentación al menos 2 años (numeral 9.3).',
    },
    {
      code: 'NOM-035-STPS-2018',
      name: 'Factores de riesgo psicosocial',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.1 al 5.8, 7.2, 7.9, capítulo 8',
      area: 'General',
      responsibleArea: 'Recursos Humanos',
      status: 'PENDING',
      dueDate: daysFrom(180),
      normName: 'Norma Oficial Mexicana NOM-035-STPS-2018, Factores de riesgo psicosocial en el trabajo — Identificación, análisis y prevención.',
      normObjective: 'Establecer los elementos para identificar, analizar y prevenir los factores de riesgo psicosocial, así como para promover un entorno organizacional favorable en los centros de trabajo.',
      applicabilityJustification: 'La norma es de aplicación obligatoria para todos los centros de trabajo del territorio nacional, independientemente de la actividad económica o número de trabajadores, con requisitos diferenciados según el tamaño de la empresa.',
      applicabilityScope: 'Aplica a la totalidad del personal de la empresa. Para centros con más de 50 trabajadores se requiere identificación de factores de riesgo psicosocial y evaluación del entorno organizacional, con informe de resultados integrado al diagnóstico de seguridad y salud.',
      specificRequirement: 'Establecer por escrito, implantar y difundir política de prevención de riesgos psicosociales, violencia laboral y promoción de entorno organizacional favorable (numeral 5.1). Realizar identificación y análisis de factores de riesgo psicosocial y evaluación del entorno organizacional al menos cada 2 años (numerales 5.2, 5.3, 7.9). Elaborar informe con resultados, conclusiones y recomendaciones disponible para trabajadores (numeral 7.7). Integrar resultados al diagnóstico de seguridad y salud NOM-030 (numeral 7.6). Adoptar medidas de prevención y control: apoyo social, capacitación, canales seguros de queja (capítulo 8). Detección de necesidades de capacitación relacionada con riesgos psicosociales al menos cada 2 años (numeral 8.2). Conservar registros de resultados, medidas de control y trabajadores examinados mínimo 1 año (numeral 5.8).',
    },
    {
      code: 'NOM-036-1-STPS-2018',
      name: 'Factores de riesgo ergonómico — Manejo manual de cargas',
      legalSource: 'NOM',
      legalBasis: 'Numerales 5.1 al 5.6, 7.2 al 7.7, 8.4, 9.2, 10.3',
      area: 'Producción',
      responsibleArea: 'Seguridad e Higiene',
      status: 'PENDING',
      dueDate: daysFrom(150),
      normName: 'Norma Oficial Mexicana NOM-036-1-STPS-2018, Factores de riesgo ergonómico en el trabajo — Identificación, análisis, prevención y control. Parte 1: Manejo manual de cargas.',
      normObjective: 'Establecer los elementos para identificar, analizar, prevenir y controlar los factores de riesgo ergonómico en los centros de trabajo derivados del manejo manual de cargas, a efecto de prevenir trastornos músculo-esqueléticos laborales.',
      applicabilityJustification: 'Los trabajadores del área de producción, almacén y mantenimiento realizan actividades cotidianas de manejo manual de cargas (levantamiento, transporte, empuje y jalado de materiales y piezas), con exposición a riesgos ergonómicos que pueden derivar en trastornos músculo-esqueléticos.',
      applicabilityScope: 'Aplica a los puestos de trabajo donde se realiza manejo manual de cargas de 3 kg o más de forma cotidiana: operadores de producción, almacenistas, mecánicos de mantenimiento y personal de carga y descarga.',
      specificRequirement: 'Elaborar análisis de factores de riesgo ergonómico por manejo manual de cargas mediante identificación de puestos, estimación simple del nivel de riesgo (Apéndices I y II) y evaluación específica cuando aplique (numerales 5.1, 7.1-7.4). Revisar y actualizar el análisis cuando cambien condiciones de trabajo o se detecten trastornos músculo-esqueléticos (numeral 7.6). Integrar análisis al diagnóstico de seguridad y salud NOM-030 (numeral 7.7). Elaborar e implantar Programa de ergonomía con fechas de ejecución no mayores a 1 año (numeral 8.4). Realizar exámenes médicos iniciales y periódicos con seguimiento anual, por médico con conocimientos en medicina del trabajo (numeral 9.2). Conservar expedientes clínicos mínimo 5 años (numeral 9.4). Capacitar a trabajadores expuestos antes del inicio y reforzar al menos cada 2 años (numerales 10.2, 10.3).',
    },
  ];

  let created = 0;
  for (const req of reqs) {
    await prisma.requirement.create({
      data: {
        code: req.code,
        name: req.name,
        legalSource: req.legalSource,
        legalBasis: req.legalBasis,
        area: req.area,
        responsibleArea: req.responsibleArea,
        status: req.status,
        dueDate: req.dueDate,
        normName: req.normName,
        normObjective: req.normObjective,
        applicabilityJustification: req.applicabilityJustification,
        applicabilityScope: req.applicabilityScope,
        specificRequirement: req.specificRequirement,
        companyId: company.id,
        createdById: admin.id,
      },
    });
    created++;
    console.log(`✓ ${req.code} — ${req.name}`);
  }

  console.log(`\n✅ ${created} requerimientos creados exitosamente para ${company.name}`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error('❌ Error:', e.message);
  process.exit(1);
});
